version: '3.3'

services:
  mipichanga-frontend:
    image: mipichanga-frontend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - mipichanga-network

networks:
  mipichanga-network:
    driver: bridge